name: List all default GitHub Vars

on:
  workflow_dispatch:

jobs:
  ubuntu-environment-variables:
    runs-on: ubuntu-latest
    steps:
      - name: List Ubuntu environment variables
        run: env

  windows-environment-variables:
    runs-on: windows-latest
    steps:
      - name: List Windows environment variables
        run: env

  macos-environment-variables:
    runs-on: macos-latest
    steps:
      - name: List macOS environment variables
        run: env
